### ISSUE TITLE
Common Ground or Positive?

### ISSUE THREAD

**Issue by 2wenty2wo** [derrickthomin/djbb-midi-box#1]
Hi,

In this picture you’ve labled common ground but looking at the wire colour and where it goes to the pinout of the pico and OLED display, it looks to be common positive. Is this a mistake in the picture? Thanks!

Shaun

![ACF2FAE8-F248-43ED-BBCE-FBB878CAE2B8](https://user-images.githubusercontent.com/11643336/172587838-7d7624a1-8b73-4bec-81d4-9b0571e8fd7c.jpeg)

**Comment by derrickthomin** [comment]
Hi! Good catch - that's totally power and not ground. Updated the pic in the readme!
